= REST API Guide
김형익;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= 개요

[[overview-http-verbs]]
== HTTP 동사

본 REST API에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 동사 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `PUT`
| 기존 리소스를 수정할 때 사용

| `PATCH`
| 기존 리소스의 일부를 수정할 때 사용

| `DELETE`
| 기존 리소스를 삭제할 떄 사용
|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있다.

| `204 No Content`
| 기존 리소스를 성공적으로 수정함.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 더 오류에 대한 정보가 담겨있다.

| `404 Not Found`
| 요청한 리소스가 없음.
|===

= 환자 정보

== 환자 등록
환자 등록은 환자 정보를 등록할 때 사용한다.
`POST` 요청을 사용하여 환자 정보를 등록 할 수 있다.

operation::register-patient[snippets='http-request,request-fields,request-body,response-body,http-response']

== 환자 조회
환자 조회는 환자정보를 조회할 때 사용한다.
`GET` 요청을 사용하여 환자 정보에 접근할 수 있다.

operation::patient[snippets='http-request,path-parameters,response-body,http-response']

== 환자 목록 조회
환자 목록 조회는 조회조건에 따라 환자의 리스트를 조회할 때 사용한다.
`GET` 요청을 사용하여 환자 리스트 정보에 접근할 수 있다.

operation::list-patient[snippets='http-request,request-parameters,response-body,http-response']

== 환자 정보 수정
환자 정보 수정은 환자의 정보를 수정할 때 사용한다.
`PUT` 요청을 사용하여 환자 정보를 수정 할 수 있다.

operation::update-patient[snippets='http-request,path-parameters,request-fields,request-body,response-body,http-response']

== 환자 정보 삭제
환자 정보 삭제는 환자의 정보를 삭제할 때 사용한다
`DELETE` 요청을 사용하여 환자 정보를 삭제 할 수 있다

operation::delete-patient[snippets='http-request,path-parameters,response-body,http-response']


= 방문 정보

== 방문 등록
방문 등록은 환자 방문 정보를 등록할 때 사용한다.
`POST` 요청을 사용하여 환자 방문 정보를 등록 할 수 있다.

operation::register-visit[snippets='http-request,request-fields,request-body,response-body,http-response']

== 환자 방문 조회
환자 방문 조회는 환자 방문 정보를 조회할 때 사용한다.
`GET` 요청을 사용하여 환자 방문 정보에 접근할 수 있다.

operation::visit[snippets='http-request,path-parameters,response-body,http-response']

== 환자 방문 정보 수정
환자 방문 정보 수정은 환자의 방문 정보를 수정할 때 사용한다.
`PUT` 요청을 사용하여 환자 방문 정보를 수정 할 수 있다.

operation::update-visit[snippets='http-request,path-parameters,request-fields,request-body,response-body,http-response']

== 환자 방문 정보 삭제
환자 방문 정보 삭제는 환자의 방문 정보를 삭제할 때 사용한다
`DELETE` 요청을 사용하여 환자 방문 정보를 삭제 할 수 있다

operation::delete-visit[snippets='http-request,path-parameters,response-body,http-response']

